import java.text.SimpleDateFormat

/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

plugins {
    id 'com.android.application'
}

android {
    namespace 'io.twoyi'
    compileSdkVersion 36

    def buildSerial = new SimpleDateFormat("MMddHHmm").format(new Date())

    defaultConfig {
        applicationId "io.twoyi"
        minSdkVersion 28
        targetSdkVersion 28
        versionCode 10354
        versionName "0.5.4-${buildSerial}"

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        resValues true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }
    ndkVersion '22.1.7171670'
}

afterEvaluate {
    base {
        archivesName = "twoyi_${android.defaultConfig.versionName}"
    }
}

tasks.register('cargoBuild', Exec) {
    workingDir file("${projectDir}/rs")
    Properties properties = new Properties()
    properties.load(project.rootProject.file('local.properties').newDataInputStream())
    def ndkPath = "${properties.getProperty('sdk.dir')}/ndk/${android.ndkVersion}"
    environment "ANDROID_NDK_HOME", ndkPath
    environment "NDK_HOME", ndkPath
    commandLine 'sh', 'build_rs.sh', '--release'
}

tasks.configureEach { task ->
    if ((task.name == 'javaPreCompileDebug' || task.name == 'javaPreCompileRelease')) task.dependsOn 'cargoBuild'
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.13.0'

    implementation 'com.github.tiann:FreeReflection:3.1.0'

    implementation "com.github.topjohnwu.libsu:core:6.0.0"

    // AboutPage
    implementation 'com.github.medyo:android-about-page:1.2.4'
    implementation 'de.psdev.licensesdialog:licensesdialog:2.2.0'
    implementation 'com.afollestad.material-dialogs:core:0.9.6.0' // com.android.support:support-annotations:27.0.1
    implementation 'moe.feng:AlipayZeroSdk:1.1'

    implementation 'org.jdeferred:jdeferred-android-aar:1.2.6'
    implementation 'com.github.clans:fab:1.6.4'

    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'
    annotationProcessor 'androidx.annotation:annotation:1.9.1'

    implementation 'org.apache.commons:commons-compress:1.28.0'
    implementation 'org.tukaani:xz:1.11'

    implementation 'com.hzy:libp7zip:1.7.0'
    implementation 'com.cleveroad:androidmanimation:0.9.1' // com.android.support:appcompact-v7:23.2.0

    implementation 'com.intuit.sdp:sdp-android:1.1.1'
    implementation 'com.intuit.ssp:ssp-android:1.1.1'
}