import java.text.SimpleDateFormat

/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'io.twoyi'
    compileSdkVersion 36

    def buildSerial = new SimpleDateFormat("MMddHHmm").format(new Date())

    defaultConfig {
        applicationId "io.twoyi"
        minSdkVersion 28
        targetSdkVersion 28
        versionCode 10354
        versionName "0.5.4-${buildSerial}"

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        resValues true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }
    ndkVersion '22.1.7171670'
}

afterEvaluate {
    base {
        archivesName = "twoyi_${android.defaultConfig.versionName}"
    }
}

tasks.register('cargoBuild', Exec) {
    workingDir file("${projectDir}/rs")
    Properties properties = new Properties()
    properties.load(project.rootProject.file('local.properties').newDataInputStream())
    def ndkPath = "${properties.getProperty('sdk.dir')}/ndk/${android.ndkVersion}"
    environment "ANDROID_NDK_HOME", ndkPath
    environment "NDK_HOME", ndkPath
    commandLine 'sh', 'build_rs.sh', '--release'
}

tasks.configureEach { task ->
    if ((task.name == 'javaPreCompileDebug' || task.name == 'javaPreCompileRelease')) task.dependsOn 'cargoBuild'
}

dependencies {

    implementation libs.androidx.appcompat
    implementation libs.material

    implementation libs.freeReflection

    implementation libs.libsu.core

    // AboutPage
    implementation libs.android.about.page
    implementation libs.licensesdialog
    implementation libs.material.dialogs.core // com.android.support:support-annotations:27.0.1
    implementation libs.alipay.zero.sdk

    implementation libs.jdeferred.android.aar
    implementation libs.fab

    implementation libs.glide
    annotationProcessor libs.glide.compiler
    annotationProcessor libs.androidx.annotation

    implementation libs.commons.compress
    implementation libs.xz

    implementation libs.libp7zip
    implementation libs.androidmanimation // com.android.support:appcompact-v7:23.2.0

    implementation libs.sdp.android
    implementation libs.ssp.android
}
